name: Build and runtest

on:
  push:
    branches:
      - main
  pull_request:

jobs:
   build:
     name: Check build
     runs-on: ubuntu-22.04
     steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix develop -c dune build
   format:
     name: Check formatting
     runs-on: ubuntu-22.04
     steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix develop -c dune build @fmt
   runtest:
     name: Run tests
     runs-on: ubuntu-22.04
     steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix develop -c dune runtest
