name: Build and runtest

on:
  push:
    branches:
      - master
  pull_request:

jobs:
   build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-version:
          - 4.10.1

    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - name: Opam setup (install dependencies)
        run: |
          opam pin add ocamlpaxos.dev . --no-action
          opam depext ocamlpaxos --yes --with-doc --with-test
          opam install . --deps-only --with-doc --with-test

      - name: Test that it builds
        run: opam exec -- dune build

      - name: Run any tests in the directory
        run: opam exec -- dune runtest
        
      - name: Ensure code is formatted
        run: |
          opam install ocamlformat --yes --with-doc --with-test
          opam exec -- dune build @fmt
